### ISSUE TITLE
老哥更新一下吧11.3驱动无效  鼠标键盘动不了

### ISSUE THREAD

**Issue by lengwangye** [LastKing/I7-9700K-Z390GamingX#1]

**Comment by LastKing** [comment]
11.3....我这还没更新到11.3.。。苹果推了11.3的更新么？

**Comment by lengwangye** [comment]
emm....老哥回复好快啊&nbsp; 。11.3beta2版



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "TooNew"<notifications@github.com&gt;; 
发送时间: 2021年2月19日(星期五) 下午2:59
收件人: "LastKing/I7-9700K-Z390GamingX"<I7-9700K-Z390GamingX@noreply.github.com&gt;; 
抄送: "冷王爷"<lengwangye@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [LastKing/I7-9700K-Z390GamingX] 老哥更新一下吧11.3驱动无效  鼠标键盘动不了 (#1)





 
11.3....我这还没更新到11.3.。。苹果推了11.3的更新么？

**Comment by LastKing** [comment]
更新了 我现在用的  0.6.6  你再试试。。
我这边 用的是非测试版本。。。

**Comment by lengwangye** [comment]
老哥 &nbsp; 还是鼠标键盘动不了



发自我的iPhone12ProMax


------------------ 原始邮件 ------------------
发件人: TooNew <notifications@github.com&gt;
发送时间: 2021年2月19日 15:16
收件人: LastKing/I7-9700K-Z390GamingX <I7-9700K-Z390GamingX@noreply.github.com&gt;
抄送: lengwangye <lengwangye@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[LastKing/I7-9700K-Z390GamingX] 老哥更新一下吧11.3驱动无效  鼠标键盘动不了 (#1)






更新了 我现在用的  0.6.6  你再试试。。
我这边 用的是非测试版本。。。

**Comment by LastKing** [comment]
这个我也没啥办法了。。。我没更新到 这么高的版本。。 0 - 0.。。。

**Comment by lengwangye** [comment]
好8-那我在找找老哥




------------------ 原始邮件 ------------------
发件人: TooNew <notifications@github.com&gt;
发送时间: 2021年2月19日 16:22
收件人: LastKing/I7-9700K-Z390GamingX <I7-9700K-Z390GamingX@noreply.github.com&gt;
抄送: lengwangye <lengwangye@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[LastKing/I7-9700K-Z390GamingX] 老哥更新一下吧11.3驱动无效  鼠标键盘动不了 (#1)






这个我也没啥办法了。。。我没更新到 这么高的版本。。 0 - 0.。。。
